### ISSUE TITLE
fontello-cli won't fetch updates after saving session in browser

### ISSUE THREAD

**Issue by lolmaus** [paulyoung/fontello-cli#16]
Hi!

I've got a `fontello.json` in my project folder, downloaded manually from fontello.com. I would like to update it with new icons by leveraging fontello-cli.

I have installed fontello-cli locally as i'm going to use it in a Grunt task:

```
npm install fontello-cli --save-dev
```

Then i do:

```
node_modules/fontello-cli/bin/fontello-cli open --config fontello.json
```

A browser window is opened with my icons already selected.

I select another icon and press "Save selection".

Then i do:

```
node_modules/fontello-cli/bin/fontello-cli install --config fontello.json --css fontello --font fontello
```

It successfully downloads the font and css files from Fontello, but the newly selected icon does not appear. The config file is also not updated with the new icon.

Please help me resolve this issue.

**Comment by kblagojevic** [comment]
I am experiencing the same problem... the downloads are missing the new icons. The only way I can add icons is to manually download, rename, and move the file.

**Comment by henrijs** [comment]
Same here.

**Comment by rootical** [comment]
Similar issue, when calling ``fontello-cli open`` from my icons directory, I expect it's initial content to be overwritten by the ``fontello-cli install`` command with new fonts and css. Instead a new folder being created with session name.

**Comment by alisman** [comment]
Ditto on this issue.  Paul are you going to do this work or would you like us to?  Happy to help out on this great project.

**Comment by paulyoung** [comment]
@alisman I'm not able to look into this right now but would be happy to discuss a solution and review a pull request if you'd like to contribute.

**Comment by derekonay** [comment]
Just wanted to see if anyone has done any work on this? 

If not I will probably take a stab at working this in.

**Comment by paulyoung** [comment]
@derekonay not that I know of, feel free!

**Comment by alisman** [comment]
Yeah, we haven't been able to invest the time.  But would be great if this
was solved. Thanks!

**Comment by derekonay** [comment]
I just want to see if I am thinking about this correctly, but couldn't we just save the session id from the browser in a variable after running fontello-cli open. Then on install the program makes a get request to the specified url + the saved session id and not the one created from the config.json?

**Comment by paulyoung** [comment]
I don't think a variable will cut it because the process exists after each command. The session ID would need to be stored in a way that it will persist after `fontello open` is run.

**Comment by EddieOne** [comment]
+1 The readme should be updated as this module doesn't work.

**Comment by lolmaus** [comment]
Nice, thanks!
