### ISSUE TITLE
Upgrade npm version

### ISSUE THREAD

**Issue by AlvaroL** [paulyoung/fontello-cli#41]
Recently a change has been merged that fixed a silent issue but no version is uploaded to NPM, could you please upload it? Thanks in advance

**Comment by AlvaroL** [comment]
in the meantime we solved it by adding the host to the command options:
`fontello-cli --config ./src/config.json install --font dist --host 'https://fontello.com'`

**Comment by dlackty** [comment]
A new version is [released on npm](https://www.npmjs.com/package/fontello-cli). Thank you!
